# ALSA configuration to set the default sound card.
#
# This configuration uses the plughw plugin to ensure audio is automatically
# converted to a format the hardware understands. It sets the default device
# to the USB sound card by its stable name, "Device".

pcm.!default {
    type plughw
    card Device
}
ctl.!default {
    type hw
    card Device
}