pcm.ext0 {
	type plug
	slave.pcm "dmixer0"
}

pcm.dmixer0  {
 	type dmix
 	ipc_key 1024
 	slave {
		pcm "hw:1,0"
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 44100
	}
	bindings {
		0 0
		1 1
	}
}

ctl.dmixer0 {
	type hw
	card 1
}

pcm.ext1 {
	type plug
	slave.pcm "dmixer1"
}

pcm.dmixer1 {
 	type dmix
 	ipc_key 1024
 	slave {
		pcm "hw:2,0"
		period_time 0
		period_size 1024
		buffer_size 4096
		rate 44100
	}
	bindings {
		0 0
		1 1
	}
}

ctl.dmixer1 {
	type hw
	card 2
}
