#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          master-controller
# Required-Start:    $remote_fs $syslog station-setup
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Harmoniscope master control daemon
# Description:       The Harmoniscope master control daemon runs on an ongoing
#                    basis, taking in station event information and triggering
#                    actions.
### END INIT INFO

# Author: Jon McClintock <jammer@weak.org>

DESC="Harmoniscope master control daemon"
DAEMON=/usr/local/bin/master_ctl.py

PIDFILE=/var/run/harmoniscope/master-controller.pid

